### ISSUE TITLE
Comparing ICPCUDA with ElasticFusion

### ISSUE THREAD

**Issue by mrkstt** [mp3guy/ICPCUDA#12]
Hi Tom,

I'm comparing the result of ElasticFusion with ICPCUDA pose.
I convert both result to homogeneous transformation matrix, however the results seem different as shown (e.g. in frame no. 5) below:

ElasticFusion:

> 0.999971 -0.00527336 0.00551413 -0.00348684
> 0.00529863 0.999976 -0.00454144 -0.00215366
> -0.00548995 0.00457042 0.999975 -0.005605
> 0.0000000000 0.0000000000 0.0000000000 1.0000000000

ICPCUDA:

> 0.999995 -0.00277173 0.00132549 0.000447368
> 0.00277131 0.999996 0.000315587 -0.00156628
> -0.00132636 -0.000311912 0.999999 -0.000628453
> 0.0000000000 0.0000000000 0.0000000000 1.0000000000

Are both of them using different coordinate format or other constraint?, is it possible to compare these methods?

note: I used raw depth input instead of using scaled one (as tum rgbd-dataset), the above is example of my own dataset, where works great in ElasticFusion.

Thanks.

**Comment by mp3guy** [comment]
They both track different things? One is raw depth frame to to raw depth frame and the other is raw depth and color frames to predicted model depth and model color.

**Comment by mrkstt** [comment]
@mp3guy Thanks.
