### ISSUE TITLE
Error: invalid device function

### ISSUE THREAD

**Issue by wine3603** [mp3guy/ICPCUDA#17]
My devices:
GeForce GTX 765M
Ubuntu 1404

Installing is good, and when I run the test:
```
./ICP ~/rgbd_dataset_freiburg1_desk/ -v
GeForce GTX 765M
Searching for the best thread/block configuration for your GPU...
Best: 224 threads, 96 blocks (3.40282e+38ms)Error: invalid device function
/home/wine/ICPCUDA-master/src/Cuda/pyrdown.cu:90
```
this error is from: 
 pyrdown.cu:90:
 `cudaSafeCall( cudaGetLastError() );`
when I cmake it, I got:
```
-- CUDA NVCC target flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wine/ICPCUDA-master/build
```
This CUDA arch works well with my ElasticFusion, I don't know how to deal
with this error.

**Comment by mp3guy** [comment]
The 765M is 3.0 https://en.wikipedia.org/wiki/CUDA

**Comment by wine3603** [comment]
@mp3guy Thanks for reply, but even I set  CUDA_ARCH_BIN to 30 or 3.0, 
the nvcc target flags is still


`-- CUDA NVCC target flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52`

and I got the same error, maybe I need to set somewhere else ?

**Comment by mp3guy** [comment]
Do it via ccmake or cmake-gui, it's not being picked up by cmake and pushed into the makefile.

**Comment by wine3603** [comment]
@mp3guy Cool! it works now ! Thank you very much !
