### ISSUE TITLE
Subset to set matching? 

### ISSUE THREAD

**Issue by antithing** [mp3guy/ICPCUDA#18]
Hi, thanks for making this code available. 
I need to match two clouds (currently vectors of points), where one is a Subset of the other.
Is this implementation suitable for this? Will it match the smaller cloud to a section of the larger? 
Or does it need both clouds to be the same size? 
Thanks again.

**Comment by joy-yjl** [comment]
> Hi, thanks for making this code available.
> I need to match two clouds (currently vectors of points), where one is a Subset of the other.
> Is this implementation suitable for this? Will it match the smaller cloud to a section of the larger?
> Or does it need both clouds to be the same size?
> Thanks again.

hi: 
Do you have  the answer about this  question?
Thanks
