### ISSUE TITLE
Master Branch Pose completely off

### ISSUE THREAD

**Issue by axelus111** [mp3guy/ICPCUDA#8]
Hi, I am currently experimenting with ICPCUDA.

When I checkout exp Branch, run it with rgbd_dataset_freiburg1_desk and feed my poses to the TUM evalutaion tool (off- or online) I get an error (rmse) from about 0.147 (about the same as stated in readme) and a plot which looks like this:
![plotwrjjtk](https://cloud.githubusercontent.com/assets/3950589/18044918/4f44baea-6dd0-11e6-84b6-e7cbbe86744a.png)

So far so good.
But when I checkout the master branch, the results are completely off:
compared_pose_pairs 593 pairs
absolute_translational_error.rmse 0.820422 m
absolute_translational_error.mean 0.765179 m
absolute_translational_error.median 0.817489 m
absolute_translational_error.std 0.295962 m
absolute_translational_error.min 0.282498 m
absolute_translational_error.max 1.258876 m
![plothc7agb](https://cloud.githubusercontent.com/assets/3950589/18044950/8675d33c-6dd0-11e6-8e00-683b3672f833.png)

any ideas?

**Comment by steevo87** [comment]
I haven't looked at the code but my first impression is that it's one of two things:

1. The two branches use a different unit (e.g. metres vs mm) to express the translation component of the pose.
2. One of the branches returns relative transformations between successive poses, and the other returns absolute transformations from the origin (possibly the first pose).

Hope that helps!

**Comment by mp3guy** [comment]
Works fine for me on master. Without more information about your OS, graphics card, graphics card driver, CUDA version, compiler, Eigen version etc... there's not much I can infer!

**Comment by axelus111** [comment]
Hi,

OS is Kubuntu 14.04.1, Graphics Card is GTX960m, Cuda Toolkit 7.5 (nvcc 7.5.17) with nvidia driver 352.99, Eigen on current master branch

**Comment by mp3guy** [comment]
Any changes to the code to speak of? As mentioned in the README, you should be using Steven Lovegrove's branches of Eigen, Pangolin and Sophus

**Comment by axelus111** [comment]
no changes to the code (clean checkout)
eigen, sophus, pangolin from the source in the readme

**Comment by mp3guy** [comment]
I'm afraid I can't reproduce. Tried on two different machines, one 14.04 and one 16.04

**Comment by axelus111** [comment]
hmm bummer. Ok I will try a fresh install

**Comment by axelus111** [comment]
Pulled/Build/Installed most recent version of eigen, pangolin and sophus. Now it works!
Thanks for your help!
