### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by simonschmeisser** [mp3guy/ICPCUDA#9]
I did not find any information about the licensing of your code? BSD? Please add it somewhere (usually at the top of each file)

Thanks
Simon

**Comment by svenevs** [comment]
@mp3guy would you be willing to consider adding a BSD compatible license to your code?  E.g. BSD 3-clause, MIT, Apache v2 (a good choice if you are worried about patents)?  I want to fork this and make some changes / remove dependencies for things I do not need, but cannot use it without a license.

A LICENSE.txt in the root of the repository is sufficient, but as @simonschmeisser mentions it's typical to include either a link to the license in each source file, or the full blown license at the top (that's what OpenCV, for example does).

I'm happy to submit a PR for you if you choose a license :)

**Comment by simonschmeisser** [comment]
@mp3guy any update?

@svenevs did you find any comparable code having a suitable license?

**Comment by thomascent** [comment]
Hey @mp3guy , any updates on this license thing? I'd love to use this code in a project I'm working on but without a license it's essentially closed source. If you could add one that'd be much appreciated!

To sweeten the deal, I actually managed to wrap this up into a ROS package, I'd be happy to contribute it, but without a license I'm technically not allowed to. Let us know, thanks!
